namespace Advent_of_Code_2024.day12;

public static partial class Day12
{
    public static class Input
    {
        public static string GetInput(InputSelector inputSelector)
        {
            return inputSelector switch
            {
                InputSelector.Example1 => GetExample1Input(),
                InputSelector.Example2 => GetExample2Input(),
                InputSelector.Example3 => GetExample3Input(),
                InputSelector.Example4 => GetExample4Input(),
                InputSelector.Example5 => GetExample5Input(),
                InputSelector.MyInput => GetMyPuzzleInput(),
                _ => throw new ArgumentOutOfRangeException(nameof(inputSelector), inputSelector, null)
            };
        }

        private static string GetExample1Input() =>
            """
            AAAA
            BBCD
            BBCC
            EEEC
            """;

        private static string GetExample2Input() =>
            """
            OOOOO
            OXOXO
            OOOOO
            OXOXO
            OOOOO
            """;

        private static string GetExample3Input() =>
            """
            RRRRIICCFF
            RRRRIICCCF
            VVRRRCCFFF
            VVRCCCJFFF
            VVVVCJJCFE
            VVIVCCJJEE
            VVIIICJJEE
            MIIIIIJJEE
            MIIISIJEEE
            MMMISSJEEE
            """;
        
        private static string GetExample4Input() =>
            """
            EEEEE
            EXXXX
            EEEEE
            EXXXX
            EEEEE
            """;
        
        private static string GetExample5Input() =>
            """
            AAAAAA
            AAABBA
            AAABBA
            ABBAAA
            ABBAAA
            AAAAAA
            """;

        private static string GetMyPuzzleInput() =>
            """
            DDDDDDDAAAAAAAAAAAAAAAAIIIIIIIIEEEEEEEERRRRRBBBBBRRRRRRRRRRRRIUUUIXIIIIIPPPPPPPPPPPPPPWWPPPPPPPPXXXXHXXUUUUUUUUUUUUUUUPWWWWWWWWWCJJJJJJZZZZZ
            DDDDDDAAAAAAAAAAAAAAAAAAIIIIIIIIEEEEEERRRRRBBBBBBBBRRRRRRRRRIIUUUIIIIIIIPIPPPPPPPPPPPPPWPPPPPPPXXXXXXXXUUUUUUUUUUUUUUUPWWWWWWWWWJJJJJJJZZZZZ
            DDCCCCCAAAAAAAAAAAAAAAAAAIIIIIIEEEEEEERRRRRBBABBBBBRRIRRRRRRIIIIIIIIIIIIIINNPPPPPPPPPPPWPWWWPPPXXXXXXXXUUUUUUUUUUUUUUUPPPWWWWWWWJJJJJJZZZZZZ
            DDCCCCAAAAAAAAAAAAAAAAAAAIIIIEEEEEEEEERRRRRBBBBBBBBRRIRRRIIIIIIIIIIIIIIIINNPPPPPHPHHPPPWWWWWWWXXXXXXXXVVUUUUUUUUUUUPUPPPPPWWWWWJJJJJJJZZZZZZ
            CCCCCCCAAAAAAAAAAAAAAAAAEIIIIIIIEEEEEERRRRRRBBBBBBBIIIIIIYIIIIIIIIIIIIIIINNNPPPPHHHHPPWWWWWWWYXXXXXXVVVUUUUUUUUUUUUPUPPPPPPWWWWJJJJJJJJZZZZZ
            CCCCCCCATTAAALAAAAAEEAAEEIIIIIIIEEEEEERRRRBBBBBBBBBIIIIIIIGDGIIIIIIIIINNNNNNPPPHHHHHPPWWWWWWXXXXXXXXVVVVVUUVUUUUUUUPPPPPPPPPPWWJJJJJJJJJZJZZ
            CCCCCCCATTAAALAAAAAEEEEEEEIIISIIIEEEEEERRRBBBBBBBBIIIIIIIIGGGGIIIIIINNNNNNNNPPPPHHHHWWWWWWWWWWXXXXVXVVVVVVVVVUUUUUPPPPPPPPPPPWJJJJJJJJJJJJZZ
            ZCCCCTTTTTAANAAAAAAEEEEEEEIIIIIIUEEEERRRRBBBBBBBBBIGIIIIIDGGGGGIIIIINNNNNNNNPPHHHHHHHWWWWWWWWXXXXXVVVVVVVVVVVUUUUPPPPPPPPPPPSJJJJJJJQJJJJJZZ
            CCCCCCCTTTATAAAAMEEEEEEEEUIUIIUUUUEEERRRBBBBBBBBBBDDIIIIIDGGGJGIIIIIINNNNNNNNNNTHHHHHWWWWWWWWWXXXXVVVVVVVVVVUUUUUPPPPPPPPPPPPSSUUJJJQJJJJJZZ
            CCCCCCTTTTTTAAAAEEEEEEEEEUUUUUUUUUUEEEUUUUBBBBBBBBBDIIDDDDGGGGGGIIIIINNNNNNNNNNTHHHHHHWWWWWWBWXVVVVVVVVVVVVVVVUUPPPPPPPPPPPPPSPUUJJJQKJJMJZZ
            CCCCCCCTAAAAAAAAAEEEEEEEUUUUUUUUUUUUUUUUUUBUBBBBDDDDDDDDDDGGGGIIIIISNNNNNNNNNNNNHHHHHWWWWWWBBWCVZZVVVVVVVVVVVVUUPPPPPPPPPPPPPPPUUUUQQQAQQQZZ
            CCCCCCCAAAAAAAAAEEEEEEEGUUUUUUUUUUUUUUUUUUUUUBBBDDDDDDDDDDGGGGGRPPPPPPNNNNNNNHHHHHHHWWWWWWWWWWWZZZZVVVVVVVVVVVVVFPPPPPPPPPPPPPPUUUUBQQQQQQQZ
            KCCCCKAAAAAAAAAAAEEEEEEEEUUUUUUUUUUUUUUUUUUUUBBDDDDDDDDDDDDGGGPRPPPPPNNNNNNNNHHHHHHHHWWWWWWWZZZZZZZVVVVVVVVVVVVVVPPPPBBPPPPPPIIUUUBBQQQQQQQQ
            KKCCCKAAAAAAAAAARRAPENNNPUPUUUUUUUUUUUUUUUUKDDDDDDDDDDDDDDDGPGPPPPPPNNNNNNNNNHHHHHHWWWYWWWWZZZZZZZZZZVVVVVVVVVVVQQBBBBBBPPPPPPIUUUUBBQQQQQQQ
            KKCCKKAYAAAAAAAAAAAPENNNPPPPUUUUUUUUUZZZZZKKKDKDMMDDDDDDDDDDPPPPPPPPPPNNNNNNNNHHHHHHWYYWWWWWWZZZZZNZZVVUVVVVVVQVQQQBBBBPPPPPPPJUBBBBQQQQQQQQ
            KKKKKKAAAAAAAAAAAAAPENNNPPPPPUUJUUUUZZZZZZKZKKKDDDDDDDDDDDDDPPPPPPPPPPIINNNNNHHHHPHHWWWWWWWWWZZZNNNZZZVUUUUUVVQQQJJQQQBBPPPMPJJJJJJQQQQQQQQQ
            KKKKKKAAAAAAAAAAAAPPPNNNPPPPPPPJUUUZZZZZZZZZZKKDDDDDDFDDDDDPPPPPPPPPPPNNNNNNNHPPPPHWWWWWWWWWWZZZNNNNNNVUUUUUUQQQQQQQQQQBBRRRRRJJJJJQQQQQQQQQ
            KKKKKKKKATAAAAAGJPPPJNNNJJPMPPJJJUUUZZZZZZZZZKKDDDDDDFDDDDDDPPPPPPPPPMMMNNNZNNPPPPWWHWWPWWWWNZZZNNNVVNVUUUKKQQQQQGGQQRQRRRRRRRJJJJJJJFQQFFFF
            KKKKKKKKKTTAAAGGJJJJJNNNJJJJJPJJJUUUUZLZZZZZZKKDDDDFFFDDDDDDDVPPPPPPPPPMNNNNCCCCPPPWHPPPWWWWNNNNNNNVVNVVVUKKQQQQQRGRRRRRRRRRRRRERJJJJFFFFFFF
            KKKKKKKKKTTTTTGGGJJJJNNNJJJJJJJJOUUUUUZZZZZZZKKDKKDFFFFFFDDDDPPPEPPXPZPMMMMMMMMCPPPPPPPPWPWWNNNNNNNVVVVVVUKKKQQQRRGRRRRRRRRRRRRRRRJZBFFFFFFF
            KKKKKKKKKTTTTTTGGGJJJNNNJJJJJJJFOOUUUUZZZZZZZKKKKKDPFFFFFFFFEEEEEDDDMMMMMMMMMMMMPPPPPPPPPPPWNNNNIINVVVVVVVKKKKBBBRGRRRRRRRRRRRRRRRRBBBFFFFFF
            KKKKKKKTKTTTTTTTTJJJJNNNJJJJJJJFOOUAUNNZZZFFZKKKHKHPFFFFFFFFEEEEEEDDDDDMMMMMMMMUPPPPPPPPPPPPPNNIIIVVVVVVVBBBKKBBRRRRRRRRRRRRRRRRRRSBBBBBFFFF
            KKKKKKTTKKTTKKKKGJJJJNNNJJJJJJJOOOOAUNNZZFFFFKKKHHHHFFFFFFFFEEEEEDDDDXXXXMMMMMMPPPPPPPPPPPPPQHNIIIVVVVVVVBBBBBBBBRRRRRRRRRRRRRRRRRRBBFFFFFFF
            KKKKKKTTTTTTKKKMMJJJJJJJJJJJJJJJOOOONNNNZNNNHHHHHHXXFFFFFFFEEDEEDNDDDDXXXXMMMMMMPPPPPPPPPPPPQHNIIVVVVVVVVBBBBBBBBBRRRRRRRRRRRRRRRRBBBBBFFFFF
            KKKKKKKTTTKKKKKMMRJJJJJJJJJJJJJJOOOOONNNNNNHHHHHHHXXFIFFFFFFDDDDDDDDDDXXXXXXMHHHPPPPHHPPPPPQQHHIIVVVVVVVVBBBBBBBBBRRFFRRRRRRRRRRRBBBBBBBFFFF
            KKKKKKKKMTKKKKKMMMJMMMMJJJJJJJJOOOOOONNNNNNHHHHHHHHHFFFFFFDRDDDDDDDDDXXXXXXXMHHHPPPPHHPPPPPPHHHIIVZZZZZBBBBBBBBBBBRKFFFFRRRRRRRBRRRBBBBBBFFF
            KKKKEEKMMOKKKJMMMMMMMMMJJSJJJJJOOOOOOONNNNGHHHHHHHHIFFFFFDDDDDDDDDDDDXXXXXXXXXHHHHPHHHHPPPPPHHZIIZZZZBBBBBBBBBBBFFKKFFFRRRFRFFFBBRRBBBBBBBBF
            KKKKKOOOMOKKKOMMMMMMMMMMMSJJJJJOOOOOOONNNNGHHHHHHHHHFFFFDDDDDDDDDDDDDDDDXXXXXXHHHHHHHHHPPPHHHHZIIZZBBBBBBBBBBBBBFFFFFFFFFFFFFFBBBBBBBBBBBBBB
            KKKKKOOOOOKKOOFMMMMMMMMMMMJJJJOOOOOOOONNNNGHHHHHHIHLFFFFFDZDDDDDDDDDDDDXXXXXXXXHHHHHHHHHPPHHHOZIZZZZZBBBBBBBBBBBFFFFFFFFFFFFFBBBBBBBBBBBBBBB
            KKKKOOOOOOOOOOMDMMMMMMMMMMFFJOOOOOOZZZNZNZGHHHHHHHHLFFFFFDDDDDDDDDDDDDDXXXXXXXXXXXXHHHHPPPHHHZZZZZZZZBBZZWWBBWWFFFFFFFFFFFFFFBBBBBBBBBEEEBBB
            KEOOOOOOOOOOOOMMMMMMMMHMMMIFFFOOOOOOZZZZZZGHHHHHHHHFFFFFFFDDDDDDDDDDDXXXXXXXXXXXHXXHHHHHHHHHHZZZZZZZZZBZZQWWWWWFFFFFFFFFFFFFFFBFBBBBBVEEBBBE
            EEOOOOOOOOOOOOMMMMMMMMHHIIIBFOOOOOOOZZZZZZGGGHBVYHHFFFFFFFPPDDDDDDDNNNXXXXXXXXXXHXHHHHHHHHHHHWZZZZZZZBBZZWWWYWWFFIFFFFFFFFFFFFFFDDBBBBBEEEEE
            EEOOOOOOOOOOOOXMMGMMZMMHIIZUUUOUUUOUUZZZZZGCVVVVVVHFFFFFFPPPDDDDDDNNNNXXXXNCXXXXHXHHHHHHHHHHHZZZZZZZZZZZZZWWWWWFFFFFFFFFFFFFFFFFDDDBBBBEEEEE
            EEEOOOOOOOOOOOOGGGMGMMHHHUUUUUUUUUUUUUZUZUCCCCVVVVEEAAFFFPPPZDDDDNNNNNNXNXNCCXCVHHHHHHHHHHHHZZZZZZZZZZZZZZWWWWWFWFFFFFFFFFFFFFFFDDDBBBBEEEEE
            EEEOOOOOOOOOOOOGGGGGMMHUUUUUUUUUUUUUUUUUUUUUCVVVVEEEEAAFPPPPZDDDNNNHNNNNNNNNCCCVCCCCHHHHHHHHZZZZZZZZZZZZZWWWWWWWWWWWFFFFZZIIIFZIIIIBEEEEEEEE
            EEEEOOOOOOOOXXGGGGGGGMMUUUUUUUUUUUUUUUUUUUUUCVVVCEEPPAAAPPPPZDDNNNNHNNNNNCCCCCCCCCCCCHHHHHHHZZZZZZZZZZZZZLWWWWWWWWWWFFFFIIIIIFFIIIOEEEEEEBEE
            EEEEEEOOOOOOXXGGGGGGGGGGGUUUUUUUUUUUUUUUUUUCCVVVEEEPPPPPPPPPPJDDNNHHNHNNCCCCCCCCCCCCCHHHHHHZZZZZZZZZZZZZZZWWWWWWWWWWFFTFTIIIIIIIIIIIEEEBEBEE
            EEEEEYYYOYYOXXXGGGGGGGGGGUUUUUUUUUUUUUUUUCCCCCCCCCEEPPPPPPPPPJJJIIHHHHNCJCCCCCCCCCCCCCCHHHHIIIIZZZTTZZDDZVJJJWWWWWWFFTTTTTIIIIIIIIIEEEBBBBBB
            EEEREEYYYYYXXXTGGGGGGGGGKUUUUUUUUUUUUUUUUCCCCCCCCCEEPPPPPPPPPJIIISSHHCCCCCCCCCCCCCCCCCCCAHHHIIIIZZTTTTJJJJJJJWWWWWWFWWWIIIIIIIIIIIIIEEBBBBBB
            HEEEEEYYYYXXTTTGGGGGGGGKKKKGUUUUUUUUAUUUCCCCCCCCCCCPPPPPPPPPJJIIISHHHHHHHCCCCCCCCCCCCCCCAAHHHIIIZEITTTTJJJJJJJWWWWWWWWIIIIIIIIIIIIIIWBBBBBBB
            HHHHHYYYYXXXXTTTGTGGGGKKKKKUUUUUUUULAAAAAWWWWWWWCCPPPPPPPPPPJJJIITHHHHHHCCCCCCCCCCCCCCCAAAAIIIIIIIITTTTTJJJJJJJWWWWWWWIIIIIIIIIIIIIIBBBBBBBB
            HHHHYYYYYYXXXTTTGTGGGGKKKKKKLLUUAUULAAAAAWWWWWWWWWWWPPPPPPPPPPTTTTHHHHHHCCCCCCCCCCCCCAAAAAAAIIIIIIIITTTTJJJJJJJWWWWWWWWIIIIIIIIIIIIICCBBBBBB
            HHHHHYYYYYYTTTTTTTTTTGGKKKKLLLULAAAAAAAABWWWWWWWWWWWPPPPWWPTPTTTTTTHHHHHCCCCCCCCCCCCCCAAAAAIIIIIIIIITTTTJJJJJJJWWWWWWVVIIIIIIIIIIIIIIIBBBBBB
            HHHHHHHHYYYUTTTTTTTTTTTTTCKKLLLLAAAAAAAABWWWWWWWWWWWPPWWWWWTPTTTTTTHHHHHHTCCCCCCCCCCCAAAAAIIIIIIIIIITTTJJJJJJJJWWWWWVVVIIIIIIIIIIIIIIBBBBBBB
            HHHHHHHHYYYUUTTTTTTTTTTUUKKKLLLAAAAAAAAAAWWWWWWWPPPPFFWWWWWTTTTTTTTHHHHHHTTTTTCCCCCAAAAAAAAAIIIIIIIIITTTJJJJJJJPWWWVVVVVVVIIIIIIIBBIBBBBBBBB
            HHHHIHIHYHHUUTTTTTTTTTTTTEKLLLLLAAAAAAAPJWWWWWWWPPPPFFWWWWWTTTTTTTTTTHHHHTTTTTCCCCJAAAAAAAAAIIIIIIIIIITTTJJPJJJPPWWVVVVVVVVIIIIIBBBBBBBBBBBB
            HHIIIIIHUUUUUUTTTTTTTTTTEEKWWLLLACAGAAAPPWWWWWWWPPPFFFFWWTTTTTTTTTTTTHHHTTTTTTTTTQJAAAAAAAAAIIIIIIIIIITCTTJPPPPPPPPVPVVVVVVTTTIIBBBBBBBBBBBB
            IIIIIIZUUUUUUTTTTTTTTTTTTTPWWWPPPPBAAPPPPWWWWWWWPPPFFFFFFLLLLTTTTVTTTTTTTTTTTTTTTQQLAAQQAAQIIIIIIIIICCCCTPPPPPPPPPPPPVVVEVEETTIIBBBBBBBBBBBB
            IIIIIIZUUUUUTTTTTTTTTTTTTDWWWWWPPPBBPPPPPWWWWWWWPFFFFFFLLLLLLLEVETTTTTTTTTTTTTTTTTQQWQQQQQQLIIIIYIIPPPCCCCPPPPPPPPPPEVVVEVEETTIIPBBBBBBBBBBB
            IIIIIIIIUUUUUUTTTTTTTTTTTWWWWWPPPBBBPPPPPPPPPPPPPPFFFFLLLLLLLLEEEEEETTTTTTTTTTTTTQQQQQQQQQQQIIIIYNIPPPPPCCCPPPBPPPPPEEEEEEETTTITPBBBBBBBBBBB
            IIIIIIKKUUUUUUTUUTTTGTGGGWWQWWPPPBBBPPPPPPPPMMPMPFFFFFLLLLLLLLEEEEEETTTTTTTTTTTTTQQQQQQQQQQQQQQYYNNNNPPCCCCCPPBPPPPPEEEEEEETTTTTBBBBBBBBBBBB
            IIIIIIIIUUUUUUUUTTTTGGGGGWJWWPPPPBBBBPPPPPMMMMMMMFFFFFLLLLLLLLEEEEEEEEEAATTTTTQTTQQQQQQQQQQQQQQQYNNNPPPCCCCCCCBBPPPEEEEEEEEETTTTBBBBBBBBBBJJ
            IIIIIIIIUUUUUUUUTTTTGGGGGWWGPPPPPPPBBPBPEPJMMMMMFFFFFFFLLLLLLLLEEEEAAEAAATAAQQQQQQQQQQQQQQQQQQHHYNNNPPPCCCCCCCCBPPPEEEEEEEEEETTTTBBHBBHHBBBB
            IIIIIIIUUUUUUUUUTTTGGGGGGGGGGPPPPPPBBBBMMJJMMMMPPFFFFFFFLLLLLLEEEEAAAAAAAAAAAQRQQQQQQQQQQQQQQHHHHJNPPPPPGGCCCCCPPPEEEEEETTTEETTTTHHHBHHBBBBB
            IIIIIIUUUUUUUUUUUUWWGGGGGGGGGPPPPPPPMBMMMMMMMMMMMFFFFFFLLLLLLLEAAAAAAAAAAAOOOOOQZZQQQQQQQQQQHHHHHHPPPPPPJGGCCCCGGGEEEEETTTTTTTTTTTHHRHHHBBBB
            MIIIIIUUUUUUUUUUUUWWWGGGGQQGGGPPPPPPMMMMMMMMMMJJJFFFFFLLLLLLALAAAAAAAAAAAAOOOOOQZZQQQQQQQQQQHHHHHHPPPPPGGGGCGGGGGGEGGEETTTTTTTTTTHHHHHHHHBBB
            IIIIIOUUUUUUUUUUUWWWWWQQQQQGPPPPPLPMMMMMMMMMMMMJJJFFXXLLLLAAAAAAAAAAAAAAAAOOOOOZZZZQQBBBBBBBWWHHHPPPPPPGGGGGGGGGGGGGTTTTTTTTHTHHHHHHHHHHBBBB
            IIIILUUUUUUUUUUUWWWWWGQQQQQQQQPPPLPMMMMMMMMMMMMJJJJFXXXXLLLLAAAAAAAAAAAAAAOOOOOYBBBBBBBBBBBBWWWHHPPPPPGGGGGGGGGGGSSSTTTTTTTTHHHHHHHHHHHHHBBB
            SIIILLUUUUUUUUUWWWWWWGQQQQQQQQQPQMMMMMMMMMMMMMMJJJJFXXXXXLAAAAAAAAAAOOOOOOOOOOOYBBBBBBBBBBBBWZHHHPPPPPGGGGGGGGGGSSSSSTTTTQQQHHHHHHHHHHHHHHHH
            SIIILLUUUUUUUUUWWWWWGGQQQQQQQQQQQMMMMMMMMVVVVMJJJJJXXXXXXXYAAAAOOOOOOOOOOOOOOYYZBBBBBBBBBBBBZZZZPPPPPPGGGGGGGGGGGSSSTTTTTTQQQHGGHHHHHHHHHHHH
            CCCCCCCUVVUUUUWWWWWQQQQQQQQQQQQQQQMMMMMMVVVZVVJJJJXXXXXXXXAAAAAOOOOOOOOOOOOOOYYZBBBBZBBBBBBBZZZPPPPPPGGGGGGGGGGGSSGRTTTTQQQQQGGGHHHHHHHHHHHH
            CCCCCCCCCCPKUUWWWWWQQQQQQQQQQQQQQQMMMMVVVVVVVVVVJXXXXXXXXXNNAALOOOOOOOOOOOOOOYYYBBBBZBBBBBBBJZZOPPPPPPPGGGGGGGGGGGGGTTTTTTQQQQMMSSHHHHHHHHHH
            SSCCCCCCCCKKWWWWWWQQQQQQQQQQQQQQQMMMMVVVVVVVVVVXXXXXXXXXBBNNDALOOOOOOOOOOOOOOYYZBBBBBBBBBBBBZZZOPPPPPPUUGGGGGGGGGGGGGTTTTTTQQZMMSSHKHKKKKKKK
            SCCCCCCCCKKWWWWWWWWQQQQQQQQQQQQQQQMMMMMVVVVVVVVQXXXXXXXXXBNNDAAOOOOOOOOOOOOOOYNNBBBBBBBBBBBBZOOOPPPPPUUUGGGGGGGGGGGGGTTTTTTQQZMMSSHKKKKKKKKK
            SCCCCCCCUKFWWWWWWWWWQQQQQQQQQQQQQEEMMMMVVVVVVVVVXXXXXXXXXXNNNAAOOOOOOXXXXXXXXYYNBBBBBBBBBBBZZOEEEEPPPUUUUGGGGGGGGGGGGGUUTZZZZMMMSMMMJJKKKKKK
            SSSCCCCCUGGGGWWWWWWWQQTQQQQQQEQQQEEMMMMMVVVVVVEEEXXXXXXXXNNNNNGOOOXXXXXXXXXXXQXNBBBBBBBBBBBZUUBEEEUUUUUUUUKGGGGGGTGGGGUUTZZZMMMMMMMMJJKKKKKK
            CCCICCCCGGGGGWWWWWWWWQQQQQQQQEEEEEEEEMMMVVVVVVEEEGXXXXXNXXNNIDGOOOXXXXXXXXXXXQQNBBBBBBBBBBBZUUUUUEUUUUUUUUUGGUGCCTTGUUUUUZZZPMMMMMMMJJKKKKKK
            CCCCCCCGGGGGGWWWWWWWWQQQQQQQQEEEEEEEEMMVVEVEVVEGEGGXRXNNDDDDDDGOOOXXXXXQQQQQQQQNNNBBBBBBBBBBBBUUUUUUUUUUUUUNCCCCCTCCCUUUUUUUUUUUUUUMMKKKKKKK
            HCCCCCCGGGGGGGGGWWWWWWWQQQQQQEEEEEEETTTTVEEEEEEGGGGXXMDDDDDDDDDGXXXXXXXXXQQQQQQQNNBBBBBBBBBBBBUUUUUUUUUUUUUUCCCCCCCCCCZUUUUUUUUUUUUMKKKKKKKK
            HCOCCCCGGGGGGGGGWWWWWKKKKQVVQEEETTTTTTTTTEEEEEEGGGGGVPXDDDDDDDDDDCCXXXXXXQHQQQQQQVBBBBBBBBBBBBUUUUUUUUUUUUUCCCCCCACCCCZUUUUUUUUUUUUOKKKKKKKK
            CCCCCCCGGGGGGGGGGGWWIKKEEEVEBBEETTTTTTTTTEEGGGGGGGGGGPPPPPDDCCCCCCCXXXXXXHHQQQQQQVBBBBBBBBBBBBUUUUUUUUUUUUCCCCCCCCCCCCCKKKUUUMMMMMOOOKKKKKKK
            CCJCWWWWGGGGGGGGGGWIIIKEEEEETBEETTTTTTTTTTTGGGGGGGGGEPBBBBDDBCCCCCCXXXXXXQHQQQZQQVBBBBBBBBBBBBUUUUUUUUUUUCCCCCCCCCCCCCKKKKUUUPPPPOOOOOKKKKKK
            GCCCCGGGGGGGGGGGGGIIIKKEEEEETTTTTTTTTTTTTTGGGGGGGGGGBBBBBBDDBBBCCCCCCRQQQHHHQQQQQVBBBBBBBBBBBBIUUUUUUUUUUUCCCCCCCCCCCCCKKKUUUPPPOOOLOYKKKQQK
            GGGGGGGGGGGGGGGGGGIIIIIEEEEETTTTTTTTTTTTTTGGGGGGGGGBBBBBBBBBBBCCCCCCCRRHHHHHQHHVVVBBBBBBBBIIIIIUUUUUUUUUUCCCCCCCCCCCCKKKKKPPPPPPPOOOYYYQQQQQ
            GGXGGGEGGGGGGGGGIIIIIIIEEEEEETTTTTTTTTTBDTGGGGGGGGGGGBBBBBBBBBCCCCCCCRRHHHHHHHHHVHHHHHIIIIIIIIMMMMUUUUUUCCCCCCCCCCCCCKKKKKKPPPPOOOOYYYYQQQQQ
            GXXGGGGGGGGGGGGGGIIIIIIEEEEETTTTTNTTTTTBDBBBGGGGGGGGGBBBBBBBBBBCCCCCCRLHHHHHHHHHHHHHHIIIIIIIIIIMUUUUUUIICCCCCCCCCCCCCKKKKKPPPPPOOPOYYYYYQQQQ
            XXXXGGGGGGGGGGGGGIIIIIIEEEEETTTTTNNETTBBBBBBGGGGGGGGGGBBBBBBBBBCCCCCCCHHHHHHHHHHHHHHIIIIIIIIIIIMMMMMUIIIICCCCCCCCCCCKKKPPPPPPPPOOPOYYYYYQQYY
            TXXGGGXCCGXGGGGGGIIIIIIEEEEEETTTTNNBBBBBBBBBBGGGGGGGGBBBBBBBBBBCCCCCCCCHHHHHHHHHHHHHIIIIIIIIIDHHMHHMUIIIICCCCIRRRRCCKKKKPPPPPPPPPPPYYYYYYYYY
            TXXXGGXXXXXGGGGGGFITTIIEEEEEEETTNNNBBBBBBBBBBBBGGGGGGBBBBBBBBBBBBCCCCCHHHHHHHHHHHHHHHHIIIWWIHHMHHHHQHHIIIIIIIIRRRRKKKKNKPUPPPPPPPPPYYYYYYYYY
            XXXXXXXXXFXYFFGGFFFTTTTTEEEEEEENNNNBBBBBBBBBBBBGGGGGGBBBBBBBBBBBBCCCCCHHHHHHHHHHHHPIIIIIIIWIHHHHHHHHHHIIIIIIRRRRRRKKKNNIINPPPPPPPPYYYYYYYYYY
            XXXXXXXXJFFFFOOGGTTTTTTTTEEEEEEENNNBBBBBBBBBBBBGGGGGBBBBBBBBBBBBBCCCCCHHHHHHHHHHPHPIIIIIWWWBHHHHHHEEIRIIIIILLRRRRRKKKNNNNNPPPPPPYYYYYYYYYYYY
            GXXXXXKXXFFFFFOOOTTTTTTTTEEEEEENNNNBBBBBBBBBBBBBGGGTRRBBBBBBBBBBBCCCCCHHHHHHHHHHPPPIIIIIWWWHHHHHHHEEIIIIIZLLLLLLLLKKKNNNTTTJPPPOYYYYYYYYYRYY
            XXXXXXXXXFFOOOOXXTTTTTTTTEEEENNNNNNNBBBBBBBBBBBBBGGTRTTBBBBBBBBBHHCCHHTHHHHHHHHHPPIIIIIWWWWWHHHHHHHEEIIIILLLLLLLIIIIKINNNTTJPPPOYYYYYYYTYRRY
            XXXXXFXXXFXXXXOXTTTTTTTTTEEEENNNNNBBBBBBBBBBBBBBBBTTTTTBBBBBBBBMMHHHHHHHBHHHHPPPPPPPPIPPWWWWUHHHHHHEEEIILMLLLLLLLIIKKINNNTTTTTTTYYYYZTTTYRRY
            XXXXFFXXFFXXXXXXXXTTTTTTTEEEEMMMMBBBBBBBBBBBBBGGNNTTTTTTTTTBTBBBHHHHHHHHHHHHHPPPPPWPPPPWWWWWWWTHHHEEEIIELLLLLLLLIIIIIITTTTTTTTTYYYYTTTTTTRRR
            XXXOXFFXFXXQXXXXXXXTTTTTTEEMMMMMMMBBBBBBBGGGGGGGGGTTTTTTTTTTTNNHHHHHHHHHHHHHPPPPPPWWPWWWWWWWWWWEEEEEEEEELLLLLLLLLIIITTTTTTTTTTRYYYYQTTTTRRGR
            XXXXXFFFFFXXXXXXXTTTTTTTTTTTMMMMMMBBBBBBLLLGGGGHGGTTTTTTTTTTTNNNHHHHHHHHHPPPPPPPCCCWWWWWWWWWWWWWEEEEEEELLLLLLLLLLILLOTTTTTTTTTTTYQQQQTTTQRRR
            XXXXFFFFFFXXXXXXTTTTTTTTTTTTTTMMMMBBMMLLLLLGGGGGGGTTTTTTTTTTTNNNHHHHHHHHHPPPPPCCCCCRWWWWWWWWWWEEEEEEEEELLLLLLLLLLLLLLTTTTTTTTTTTTQQQQTTQQRQQ
            FFFFFFFFFFXXXXXXTTTTTTTTTTTXTTTMMMMMMMLLLLGGGGGGGGTTTTTTTTTTTTNVHHHHHHHHHHHPCCCCCCCCCWWWWWWWWEEEEEEEEEEVLLLLLLLLLLLLLTTTTTTTTTTTTQQQQTQQQQQQ
            FFFFFFFFXXXXXXXXTTTTTTTTTXXXTSTXXMMMMLLLLLLLGGLTTTTTTTTTTTTTTVVVHHHHHHHHHHHCCCCCCCCCWWWWWWWWWWWWEEEEVVVVVVLVVLLVVVBBWWTTTTTTTTTTTTQQQQQXQXXQ
            FFFFFFFFFXXXXXXXXTTTTTTTTTXXXXXXXXMMMMMLLLLLLOLDDDDDTTTTTTTQQQQQHWHHHHHHHCCCCCCCCCCCCWWWWWWWWWWWEWWEVVVVVVVVVVLVVVBBBWTTTTTTTTTTTTQQQQQXXXXX
            FFFFFFFFFFXXXXXXJJTTTTTTTMXXXXXXXXXMIIMLLLLLLLLDDDDTTTTTTQQQQQQHHHHHHHHHHCCCQCCCCCCCWWWWWWWWWWWLWWWVVVVVVVVVVVVVVVPBBWTTTTTTTTTTTTQQQQQQQXXX
            FFFFFFFFFFFXXXXJJTTTTTTTTMMXXXXXXXIIIILLLPLLDRDDDDDTTTTQTQQQQQEHHHHHHHHHHHHCCCCCCCZCWWWWWWWWWWWWWWWVVVVVVVVVVVVVVBBBBWTTTTTTTTTTTTQQQQQQQQXX
            FFFFFFOFFFOIXIJJJJJJJJJJJXXXXXXXXXIIIIIELPLLDDDDDDDDTTQQQQQQQQEEHEEHHHHHHRRRRRCCCCZCEEWWWWWWWWWWWWWVVVVVVVVVVVVVVVBBBBTTTTTTTTTTTQQHHHQQQQXQ
            FFFFOOOOOOOIIIIJJJJJJJJJJXXXXXXXUIIIIIIELILLDDDDDDDDTTQQQQQQQQEEEEHHHHVVVVVRRRCCJJJJJJWJJWWWWSDDWWWVVVVVVVVVVVVVBBBBBBBBTBBBBTTRTHHHHHHHHQXQ
            FFFFFFFOOOIIIIIJJJJJJJJJXXXXIXXUUIIIIIIIIIIIEDDDDDDDQTQQQQQQQQEEVVVVVVVVVVVRRRCCJJJJJJMEEWWWSSSDSSWVVVVVVVVVVVVBBKBBBBBBBBBBBTTRRHHHHHHHQQQQ
            FFFFFFOOOIIIIIYZJJJJJJJJIEIXIXUUUUIIIIIIIIIEEEEDDDDAQQQQQQQEEEEOVVVVVVVVVVVRRRCCJJJJJJJETTTTSVSDSSSVVVVVVVVVVVVBBBBBBBBBBBBBRRRRHHHHHHQHQQQQ
            FFFFFFFOOOIYYYYJJJJJJJJIIIIIIUUUUUIIIIIIIIIEEEDDDDAAAQQQQQQEEEOKVVVVVVVVVVVRRRRRJJJJJJJEEETTSSSSSSSVVVVVVVVVVBBBBBBBBBBBBBBRRRRDHHHHHHQQQQQQ
            FFFFFFFOOOOOYYYYYYYYJJIIIIIIIUUUUPIIIIIIIIIEEEDEDDDAAQQQQQQOEOOOOOOLXXVVVVVRRRRJJJJJJJOEEEEESSSSSSSSSVVVVVVVVBBBBBBBBFBFBBBBBDDDDDHHQQQQQQQQ
            FHHFFOOOOOOOOYYYYYJJJJIIIIIIPUUUPPPPIIIIIIQQQEEEEDAAAAAQXQOOOOOOOOOOXXVVVVVRRRRJJJJJJJJEEEESSSSSSSSSVVVVVVVVJBJJBBBBBFFFBBBTTTDDDDHHQQQQQQQQ
            HHHHFOOOOOOJOYYYYYJJJJIIIIIPPPUPPPPPIIIIIQQPPQQAAAAAAAXXXXOOOOOOOOOOXXVVVVVRJJJJJJJJJJJEEEESSSSSSSSVVVVVVJJJJJJJBBBBFFFFFBBTDDDDDDHHHQQQQQQQ
            HHOOOOOOOOOOOYYYYYJJJJIIIIIIPPPPPPPPQQQQQQQQQQQAAAAAAAXXXXOOOOOOPOOOOXXXXXXRRJJRJJJEEEEEEEEEEESSSSSSVVVVVJJJJJJJJBBBFFFFFFBTDDDDDDDMQQQQQQQQ
            HHHOOOOOOOOJJJJYJJJJJGGGIIIIPPPPPBPQQQQQNQQQQQQQQAAAAAAXXXOOOOOOOOOXXXXXXXRRRRRRJJJJEEEEEEEEEEESSSSSSVVVVDJAJJJJJJFFFFFFFFSDDDDDDDDQQQQQQQQQ
            HHHHOOOOOOOJJJJJJJJJJGGGGGIPPPPPPBBQQQQQNNNNQQQQQAAAAAAAAXOOOOOOOOOXXXXXXXRRRRRRRRJEEEEEEEEEEEEEESSSSSVVSSAAJJJJJJFFFFFFFFDDDDDDDDDQQQQQQQQQ
            HHHHHOOOOJJJBBBBBJJJGGGGGIIIPPPPPBBQQQQQNNNDQQLAAAAAAAAAXXXOOOOOOOXXXXXXJXRRRRRRREJEEEEEEEEEGEEEESSSSSSSSSSSBJJJJJJSFFFFFFFFDDDDDDDQQQQQQQQQ
            HHHHHHHHHHJJBBBBBBBGGGGGGGIIIIPPPBBBQQQQNDNDQQLLAAGAKKKKXXXXXONOOOXXXXXXJXXRRRRRREEEEEEEEEEELEKEELSSSSSSSSSYJJJJJJJSFFFFFFLDDDDDDQQQQQQQQQQQ
            HHHHHHHHBJJJBBBBBBBGGGGGEIIIIIPPPPBQQQQQDDNDLLLLLGGGGKKKXXXXXKNNOOXXXXXXJXRRRRRRRUEEEEEEEEELLLLEILLLLSSSSSSYJJJJJJJYFJJJFJJJDDDDDDQQQQQQQQQQ
            HHHHHHHHBBBBBBBBBBBGGGGGGGGIIPPPPPPDDQQQDDDDLLLLLGGGGKKKKKXXXKNOOOJJJXJJJRRRRRRRREEEEEEEEELLLLLLLLLLLSSSSSSJJJJJJJJYYJJJJJJWDDDDDDQQQYYYQQQQ
            HHHHHHHBBBBBBBBBBBBBGGGGGGGBBBBBPPDDDDDDDDDDLLLZLLGGGKKKKKKKKKNNNOJJJJJJJRRRRRRDDDDDEEEEEELLLLLLLLLLLLLSSSJJJJJJJJJYYYJJJJJJDDDKQQQQYYYYYQQQ
            HHHHHHBBBBBBBBBBBBBBGGGGGGGGBBBBMMDDDDDDDDDDLLLLLGGGGKKKKKKKKKNJJJJJJJJJJJRRRRRDDDDDDDELLELLLLLLLLLLLLLLLSCCAJJJJJYYYJJJJJJJJJDGQQGGYYYYYQQQ
            HHHHHHHHBBBBBBBBBBBBGGGGGGGGGBBMMDDDDDDDDDDLLLLLLGKKGKKKKKKKKKNJJJJJJJJJJJJRRRDDDDDDDEELLLLLLLLLLLLLLLLLASACAAAYJYYYYYYJXJJJJKGGGGGGGAYYQQQQ
            HHHHHHHBBBBBBBBBBGGGGGGGGGGBBBBMMMDDDDDDDDDDLLRLXXKKKKKKKKKKKKNNUUJJJJJJJJJRRRRDDDDDDELLLLLLLLLLLLLLLLLAAAACAAAYJYYYYYYJXXEEJGGGRRRRAAYYIQQQ
            HHHHHHBBBBBBBBBBBGGGGGGQQQGQBQQMMMDDDDILLLDLLLLLXXXKKKKKKKKKKNNNNUUJJUUJJJJJRJJJDDDDLLLAAAAALLLLLLLLLLIAAAAAAAAYYYYYYYXXXXXEEEGGRRRRGAYQQQQA
            HHHHHHBBBBBBBBBBBBGHGGGQQQQQQQQMMMIIIIILHLLLLLQQXXXXXKKKKKKKKKNNNUUUUUUJJJJJJJJJJJDAAAAAAAAAALLLLLLLLAIAAAAAAAAAYYYYYXXXXXXGGGGGRRRRGAAAAAAA
            HHHHHHHBBBIBBBBBBHHHGQQQQQQQQQQMIIIIIIIIIILLDDXQXXXXXXJJKKKKKKNNNNUUUUUUUUJJJJJJJAAAAAAAAAAAALLLLLLLLAAAAAAAAAAYYYYYYYYYYXXGGGGGRRRRGAAAAAAA
            HHHHHHHHHIIIBBHBBHHHQQQQQQQQQQQMMIIIIIIIIIILIIXXXXXXXJJJKJJKKKNNNUUUUUUUUJJJJJJJJJGGAAAAAAAAALLLLLLLAAAAAAAAAAAAYYYYYYYYYYYYGGGGRRRRAAAAAAAA
            HHHHHLLHHHHHBBHHHHHQQQQQQQQQQQQQIIIIIIIIIIIIIICCCCCCCCCJJJJJJUUUUUUUUUUUDUJJJJJJJGGAAAAAAAAAALLLLLLZOOAAAAAAAAAAAYYYYYYYYYGGGGGGRRRRGAAAAAAA
            HLHHLLLLHHHHHHHHHHHHFQQQQQQQQQQQQIIIIIIIIIIIIICCCCCCCCCJJJJJJOOUUUUUUUUUUUJJJJJJJJAAAAAAAAAAALDDVVLZOOOAAAAAAAAAAYYYYYYYYYYYGGVGRRRRPAAAAAAA
            HLLHLLLDHHHLHHHHHHHHQQQQQQQQQQQQQIIIIIIIIIIIHICCCCCCCCCJJJJJJJJJJUUUUUUUUUJJJJJJJJIIIAAAAAAAAXDDVVVOOOOAAAAAAAAAAAAYYYYYYYYYKKGGRRRRPAAAAAAA
            HHLLLLLLLLHLLHHHHHHHXQQQQQQQQQQQUUIIIIIIIIIIHICCCCCCCCCCCCCJJJJJJUUUUUUUUUJJJJJJJJJIIAAAAXYXXXXXVVVVOAAAAAAAAAAAAAAYYYYYYCCCKKGGRRRRPPPPZZZA
            LLLLLLLLLLLLLHYHHHHHXQQQQQQQQQQQUIIIIIIIIIIIIICCCCCCCCCCCCCJJJJJJUUUUUUUUUUMPJSJIIIIIIACXXXXXXXXVVVVAAAAAAAAAAAAAAYYYYYYYCCCKKRRRRRRPPPPMZZZ
            LLLLLLLLLLLLLLYYYYYYXXXXQQQQQQQIIIIIIIIIIIIIIICCCCCCCCCCCCCJJJJJJUUUUUUUUMMMMSSSISIIIICCCXXXXXXXXVVVVVVVAAAAAAAALLYYYYYCCCCCCCPPPPPPPPPPZZBZ
            LLLLLLLLLLLLVYYYYYYYXXXXXQQQQQQIIIIICCIIIIIIIICCCCCCCCCCCCCCCJJJJUUUUUMMMMMMMMSSSSSSSICXXXXXXXXXXXXXVVVVAAVAAALLLLYYYYYCCCCCCCCCPZPPPPPPZZZZ
            LLLLLLLLLLLLVYYYYYYXXXXXQQQQQQIIIIIIIIIIIIIIMIGGGGGGGUCCCCCCCJJJJJUUUUMMMMMMMSSSSSSSSSSUXXXXXXXXXXXVVVVVAAVAVAALVCYYYYCCCCCCCCCCPPPPPPPPPPOO
            LLLLLLLLLLLLYYYYYYXXXXXXQQQYIQIIIIIIIIIIIIIIMGGGGGGGGGCCCCCCCJJJJJJJUUMMMMMMSSSSSSSSSSSSXXXXXXXXXXXVVVVVVVVVVVVVVCYYYYCCCCCCCCCCPPPPPPPPPOOO
            LLLLLLLLLLLLYYYYYYXXXXXXXQXIIIIIIIIIIUIIIIIIMGGGGGGGAACCCCCCCJJJCJUUUUMMMMMMSSSSSSUSSSSFXXXXXXXXXXXVVVVVVVVVVVVGVCGGGEEECCCCCCCCCPPPPPPPPOOO
            LLLKLLLLLLLYYYYYYYXXXXXXXQIIIIIIIIIIIUUIIIMMMGGGGGGAAWWWWJJJJJJCCJUUUUMMMMMMSSKKKSUSSSSXXXXXXXXXXXXXVVVVVVVVVVVGCCGGEEEEFCCCCCCCCPPPPPPPPOOO
            LLKKLLYLLLYYYYYYYYLLXXXXXXXXIIIIIIIIIUMMMIIMMMGGMMGAAAWWWJJJJJJJCCCMMMMMMMMMMMKKKKWWWZZXXXXXXXXXXXXVVVVVVVVVXGVGGGGEEEEEFCCCCCCCCPPPPPPPPOOO
            LKKKKYYYYYYYYYYYYYSLXXLXLLIIIIIIIIIIIUMMMMMMMMMMMGGAAWWWWJJJJJJCCCCCCMMMMMMMMKKWKWSWWZZXZZXXXXXXMMXVVVVVVVVXXGGGGEGEEEEEFCCFCCCCCPPPPYYROOOO
            LKKKKKYYYYYYYYYYYYYLXXLXLLIIIIIIIIYYYYMMMMMMMMMMMWWAAAWWWWJJJJCCCCCCMMMMMKKKKKKWWWWWWZZZZZXXXXXXMVVVVVVVVVVXXGXEEEEEEEEEFFFFCCFPPPPPPRRRRROO
            KKKKKKKYYYYYYYYYYLYLLLLLLLLIIIIMIIIYYYMMMMMMMMMMMWWWWWWWWWCJJCCCCCCCMMMMKKKKKKWWWWWWWZZZZZXXRXXRMVVVVVXXXXXXXGXXEETEEEEFFFFFFFFPPPPPPPRRRROR
            KKKKKKYYYYYYYYYYYLLLLLLLLLIIIMMMMIMMYYYMMMMMMMMMMMWWWWWWWWCCCCCCCCCCMMDKKKKKKKWWWWWWWWZZZZXXRRRRRRRVVVVVLXXXXXXXXETFFFFFFFFFFFFFPPPPPRRRRRRR
            KKKKKKYYYYYYYYYYYLLLLLLLLLMMMMMMMMMYYYYYMMMMSSMSMSWWWWWWWCCCCCCCCCCCMMDCFCKKKWWWWWWWWWZWWZZRRRRRRRRVVVXXXXXXXXXXXXXXFFFFFFFFFFFPPPPPPRRRRRRR
            KKKKKKKYYYYYYYYYLLLLLLLLLLLLLMMMMMMMMYYSSSSSSSSSSSWWWWWWWCCCCCCCCCCCCCCCFCKKKKWWWWWWWWWWZZZZRRRRRRRVVVHXXXXXXXXXXXXXXFFFFFFFFFFFPPFIIIRRRRRR
            KKKKKKKKYYYYYYYYKKLLLLLLLLLLLMMMMMMMMSSSSSSSSSSSSSWWWWWWWWWCCCCCCCCCCCCCCCKKKKKKWWWWWWKWRRRRRRRHRRRRVHHXXXXXXXXXXXXFFFFFFFFFFFFFFFFIIIRRRRRR
            KKKKKKKKKKYYKYYKKKLLLLLLLLLLMMMMMMMMMSSSSSSSSSSSSSWWWWWWWWCCCCCCCCCCCCCCCKKKKKKWWWWWWWKKRCRRRRHHHHHHHHXXXXXXXXXXXXXXFFFFFFFFFFFFFIIIIIIIRRDR
            KKKKKKKKKKKKKKKKKKLLLLLLLLLLLMMMMMMMMSSSSSSSSSSSSSRRRRWWWWCCCCCCCCCCCCCCCKKKKKKWWWWWWKKKKRRRRRHHHHHHHHHXXXXXXXXXXXXFFFFFFFFFFFFFFIIIIIIIIRDD
            KKKKKKKKKKKKKKKKKKLLLLLLLLLLMMMMMMMMMRSSSSSSSSSSSSRRRRRRRVVCCVVVVVCCCCCCCKKKKKKKKWWKKKKKKKRRRRHHHHHHHHXXXXXXXXXXXXFFFFFFFFFFFFFFFIIIIIIIIIDD
            KKKKKKKKKKKKKKKKKKLKLLLLLLLMMMMMMMMMMMKSSSSSSSSSSSSSRRRRVVVVVVCCCCCCCCCCCKKKKKKKKKWKKKKKKKRRRRRHHHHHHHXXXXXXXXXXXXXFFFFFFFFFFFFFFFIIIIIIIDDD
            KKKKKKKKKKKKKKKKKKKKKKKLMMMMMMMMMMMMMMKSSSSSSSSSSSSRRRRRRRRVCCCCCCCCHHCCCKKKKKKKKKKKKKKKRRRRHHHHHHHHHHXXXXXXXXXXXXXXFFFFFFFFFFFFFIIIIIIIIDDD
            """;
    }
}